# Generated by Django 4.2.4 on 2024-03-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='card-example.png', upload_to='images/'),
        ),
    ]
