# Generated by Django 4.2.4 on 2024-05-09 00:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_en', models.TextField()),
                ('description_en', models.TextField()),
                ('name_ua', models.TextField()),
                ('description_ua', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='reactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app.author'),
        ),
    ]
