# Generated by Django 4.2.4 on 2024-08-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_article_reactions_article_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ua', models.TextField(default='')),
                ('text_en', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='card-example.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_ua',
            field=models.CharField(max_length=100),
        ),
    ]
