# Generated by Django 4.2.4 on 2025-02-06 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Время, когда статья станет доступной'),
        ),
    ]
