# Generated by Django 4.2.4 on 2025-02-12 10:33

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_article_is_published_article_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Час, коли стаття стане доступною'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
