# Generated by Django 4.2.4 on 2025-10-16 15:34

from django.db import migrations
from django.utils.text import slugify

def fill_slugs(apps, schema_editor):
    Article = apps.get_model('your_app', 'Article')
    Author = apps.get_model('your_app', 'Author')
    Category = apps.get_model('your_app', 'Category')

    for obj in Article.objects.all():
        if not obj.slug:
            base_slug = slugify(obj.name)
            slug = base_slug
            n = 1
            while Article.objects.filter(slug=slug).exclude(id=obj.id).exists():
                slug = f'{base_slug}-{n}'
                n += 1
            obj.slug = slug
            obj.save()

    for obj in Author.objects.all():
        if not obj.slug:
            base_slug = slugify(obj.name_en)
            slug = base_slug
            n = 1
            while Author.objects.filter(slug=slug).exclude(id=obj.id).exists():
                slug = f'{base_slug}-{n}'
                n += 1
            obj.slug = slug
            obj.save()

    for obj in Category.objects.all():
        if not obj.slug:
            base_slug = slugify(obj.name_ua)
            slug = base_slug
            n = 1
            while Category.objects.filter(slug=slug).exclude(id=obj.id).exists():
                slug = f'{base_slug}-{n}'
                n += 1
            obj.slug = slug
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('your_app', 'previous_migration_name'),
    ]

    operations = [
        migrations.RunPython(fill_slugs),
    ]

